/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;

import Class.Capteur;
import Class.CapteurExterieur;
import Class.CapteurInterieur;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Quentin
 */
public class FenetreAlerte extends javax.swing.JPanel {

    /**
     * Creates new form FenetreAlerte
     * @param listeCapteurExt
     * @param listeCapteurInt
     * @param listeAlerte
     */
   

    public FenetreAlerte(Set<CapteurExterieur> listeCapteurExt, Set<CapteurInterieur> listeCapteurInt, Map<Capteur,Float> listeAlerte ) {
        initComponents();
        DefaultTableModel  model = (DefaultTableModel) jTable1.getModel();
        
        if ( listeCapteurInt != null)
        {
            for ( CapteurInterieur capt : listeCapteurInt)
            {
                if ( listeAlerte.containsKey(capt))
                model.addRow(new Object[]{capt.getIdentifant(),listeAlerte.get(capt)});
                else
                model.addRow(new Object[]{capt.getIdentifant(),""});

            }
        }
        if (listeCapteurExt != null)
        {
            for (CapteurExterieur capt : listeCapteurExt)
            {
                if ( listeAlerte.containsKey(capt))
                model.addRow(new Object[]{capt.getIdentifant(),listeAlerte.get(capt)});
                else
                model.addRow(new Object[]{capt.getIdentifant(),""});

            }
        }
        
        
    }
    
    public DefaultTableModel getTable ()
    {
        return (DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Capteur", "Valeur (null si pas d'alerte)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
